### ISSUE TITLE
Can't install drip on django 1.11.5

### ISSUE THREAD

**Issue by suhaboncukcu** [zapier/django-drip#60]
[✓] pip install django-drip
[✓] Add 'drip' to your installed apps
[✓] Set DRIP_FROM_EMAIL
[✗] python manage.py migrate drip

```
....
....from django.db.models.related import RelatedObject
ImportError: No module named related
```
--------------------------------
pip                   9.0.1  
Django                1.11.5  
django-drip           0.7.1

**Comment by charettes** [comment]
Duplicate of #59.
